import Head from "next/head";
import dynamic from 'next/dynamic';
import {lazy} from 'react';

const DynamicWithOptional = dynamic(() => import('@/components/example'));
const LazyWithOptional = lazy(() => import('@/components/example'));

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LazyWithOptional req="World" />
        <DynamicWithOptional req="world" />
      </main>
    </>
  );
}
